apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: lta-dev

images:
  - name: test-assessment
    newTag: v0.94

replicas:
  - count: 2
    name: test-assessment
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: test-assessment
      env: dev
patches:
  - target:
      kind: Service
      name: test-assessment
    path: patch-svc-nodeport.yaml
