apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
patches:
  - target:
      kind: service
      name: test-assignment
    path: patch-svc-nodeport.yaml

namespace: lta-prod

images:
  - name: test-assignment
    newTag: v0.94

replicas:
  - count: 3
    name: test-assignment
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: test-assignment
      env: prod
